-- Made with 'mini.colors' module of https://github.com/echasnovski/mini.nvim

if vim.g.colors_name ~= nil then vim.cmd('highlight clear') end
vim.g.colors_name = "vscode"
local yellow = "#FFEA00"

-- Highlight groups
local hi = vim.api.nvim_set_hl

hi(0, "@annotation", { fg = yellow })
hi(0, "@attribute", { fg = yellow })
hi(0, "@attribute.builtin", { fg = "#00ceb0" })
hi(0, "@boolean", { fg = "#369ce9" })
hi(0, "@character", { fg = "#e08762" })
hi(0, "@character.special", { link = "SpecialChar" })
hi(0, "@comment", { fg = "#5d9d3c", italic = true })
hi(0, "@comment.error", { bold = true, fg = "#ff2b38" })
hi(0, "@comment.note", { bold = true, fg = "#00ceb0" })
hi(0, "@comment.todo", { link = "Todo" })
hi(0, "@comment.warning", { bold = true, fg = "#e0b85e" })
hi(0, "@conditional", { link = "@keyword.conditional" })
hi(0, "@constant", { fg = "#4ec1ff" })
hi(0, "@constant.builtin", { fg = "#369ce9" })
hi(0, "@constant.macro", { fg = "#00ceb0" })
hi(0, "@constructor", { fg = "#369ce9" })
hi(0, "@constructor.python", { fg = "#00ceb0" })
hi(0, "@decorator", { link = "Identifier" })
hi(0, "@define", { fg = "#d873d2" })
hi(0, "@diff.delta", { link = "DiffChange" })
hi(0, "@diff.minus", { link = "DiffDelete" })
hi(0, "@diff.plus", { link = "DiffAdd" })
hi(0, "@error", { fg = "#ff2b38" })
hi(0, "@event", { link = "Identifier" })
hi(0, "@exception", { link = "@keyword.exception" })
hi(0, "@field", { link = "@variable.member" })
hi(0, "@float", { link = "@number.float" })
hi(0, "@function", { fg = yellow })
hi(0, "@function.builtin", { fg = yellow })
hi(0, "@function.macro", { fg = yellow })
hi(0, "@function.method", { fg = yellow })
hi(0, "@ibl.indent.char.1", { fg = "#404040", nocombine = true })
hi(0, "@ibl.scope.char.1", { fg = "#707070", nocombine = true })
hi(0, "@ibl.scope.underline.1", { sp = "#707070", underline = true })
hi(0, "@ibl.whitespace.char.1", { fg = "#404040", nocombine = true })
hi(0, "@include", { link = "@keyword.import" })
hi(0, "@interface", { link = "Identifier" })
hi(0, "@keyword", { fg = "#369ce9" })
hi(0, "@keyword.conditional", { fg = "#d873d2" })
hi(0, "@keyword.exception", { fg = "#d873d2" })
hi(0, "@keyword.import", { fg = "#d873d2" })
hi(0, "@keyword.repeat", { fg = "#d873d2" })
hi(0, "@keyword.return", { fg = "#d873d2" })
hi(0, "@label", { fg = "#98dcff" })
hi(0, "@lsp.mod.deprecated", { link = "DiagnosticDeprecated" })
hi(0, "@lsp.type.class", { link = "@type" })
hi(0, "@lsp.type.comment", { link = "@comment" })
hi(0, "@lsp.type.comment.c", { fg = "#584e44" })
hi(0, "@lsp.type.comment.cpp", { fg = "#584e44" })
hi(0, "@lsp.type.decorator", { link = "@attribute" })
hi(0, "@lsp.type.enum", { link = "@type" })
hi(0, "@lsp.type.enumMember", { link = "@constant" })
hi(0, "@lsp.type.event", { link = "@type" })
hi(0, "@lsp.type.function", { link = "@function" })
hi(0, "@lsp.type.interface", { link = "@type" })
hi(0, "@lsp.type.keyword", { link = "@keyword" })
hi(0, "@lsp.type.macro", { link = "@constant" })
hi(0, "@lsp.type.member", { link = "@function" })
hi(0, "@lsp.type.method", { link = "@function.method" })
hi(0, "@lsp.type.modifier", { link = "@type.qualifier" })
hi(0, "@lsp.type.namespace", { link = "@module" })
hi(0, "@lsp.type.number", { link = "@number" })
hi(0, "@lsp.type.operator", { link = "@operator" })
hi(0, "@lsp.type.parameter", { link = "@variable.parameter" })
hi(0, "@lsp.type.property", { link = "@property" })
hi(0, "@lsp.type.regexp", { link = "@string.regexp" })
hi(0, "@lsp.type.string", { link = "@string" })
hi(0, "@lsp.type.struct", { link = "@type" })
hi(0, "@lsp.type.type", { link = "@type" })
hi(0, "@lsp.type.typeParameter", { link = "@type" })
hi(0, "@lsp.type.variable", { link = "@variable" })
hi(0, "@lsp.typemod.keyword.controlFlow", { fg = "#d873d2" })
hi(0, "@lsp.typemod.property.readonly", { link = "@constant" })
hi(0, "@lsp.typemod.type.defaultLibrary", { link = "@type.builtin" })
hi(0, "@lsp.typemod.variable.constant", { link = "@constant" })
hi(0, "@lsp.typemod.variable.readonly", { link = "@constant" })
hi(0, "@markup.heading", { bold = true, fg = "#369ce9" })
hi(0, "@markup.heading.1.delimiter.vimdoc", { nocombine = true, sp = "#d4d4d4", underdouble = true })
hi(0, "@markup.heading.1.markdown", { bold = true, fg = "#369ce9" })
hi(0, "@markup.heading.2.delimiter.vimdoc", { nocombine = true, sp = "#d4d4d4", underline = true })
hi(0, "@markup.heading.2.markdown", { bold = true, fg = "#e08762" })
hi(0, "@markup.heading.3.markdown", { bold = true, fg = yellow })
hi(0, "@markup.heading.4.markdown", { bold = true, fg = "#5d9d3c" })
hi(0, "@markup.heading.5.markdown", { bold = true, fg = "#369ce9" })
hi(0, "@markup.heading.6.markdown", { bold = true, fg = "#d873d2" })
hi(0, "@markup.italic", { fg = "#d4d4d4", italic = true })
hi(0, "@markup.link", { link = "Underlined" })
hi(0, "@markup.link.label", { fg = "#98dcff", underline = true })
hi(0, "@markup.link.url", { fg = "#d4d4d4", underline = true })
hi(0, "@markup.list.checked", { link = "Todo" })
hi(0, "@markup.list.unchecked", { link = "Todo" })
hi(0, "@markup.raw", { fg = "#d4d4d4" })
hi(0, "@markup.raw.markdown", { fg = "#e08762" })
hi(0, "@markup.raw.markdown_inline", { fg = "#e08762" })
hi(0, "@markup.strikethrough", { fg = "#d4d4d4", strikethrough = true })
hi(0, "@markup.strong", { bold = true, fg = "#369ce9" })
hi(0, "@markup.underline", { fg = "#e0b85e", underline = true })
hi(0, "@method", { link = "@function.method" })
hi(0, "@modifier", { link = "Identifier" })
hi(0, "@module", { fg = "#00ceb0" })
hi(0, "@module.builtin", { link = "Special" })
hi(0, "@namespace", { link = "@module" })
hi(0, "@number", { fg = "#a7d58e" })
hi(0, "@number.float", { fg = "#a7d58e" })
hi(0, "@operator", { fg = "#d4d4d4" })
hi(0, "@parameter", { link = "@variable.parameter" })
hi(0, "@property", { fg = "#98dcff" })
hi(0, "@punctuation.bracket", { fg = "#d4d4d4" })
hi(0, "@punctuation.delimiter", { fg = "#d4d4d4" })
hi(0, "@punctuation.special", { fg = "#d4d4d4" })
hi(0, "@regexp", { fg = "#ff2b38" })
hi(0, "@repeat", { link = "@keyword.repeat" })
hi(0, "@storageclass", { link = "@keyword.storage" })
hi(0, "@string", { fg = "#e08762" })
hi(0, "@string.escape", { link = "@string.special" })
hi(0, "@string.regex", { link = "@string.regexp" })
hi(0, "@string.regexp", { fg = "#e08762" })
hi(0, "@string.special", { link = "SpecialChar" })
hi(0, "@string.special.url", { link = "Underlined" })
hi(0, "@stringEscape", { bold = true, fg = "#e08762" })
hi(0, "@structure", { fg = "#98dcff" })
hi(0, "@tag", { fg = "#369ce9" })
hi(0, "@tag.attribute", { fg = "#98dcff" })
hi(0, "@tag.builtin", { fg = "#369ce9" })
hi(0, "@tag.delimiter", { fg = "#808080" })
hi(0, "@text", { fg = "#d4d4d4" })
hi(0, "@text.danger", { link = "@comment.error" })
hi(0, "@text.diff.add", { link = "@diff.plus" })
hi(0, "@text.diff.delete", { link = "@diff.minus" })
hi(0, "@text.emphasis", { link = "@markup.italic" })
hi(0, "@text.literal", { link = "@markup.raw" })
hi(0, "@text.note", { link = "@comment.note" })
hi(0, "@text.strike", { link = "@markup.strikethrough" })
hi(0, "@text.strong", { link = "@markup.strong" })
hi(0, "@text.title", { link = "@markup.heading" })
hi(0, "@text.underline", { link = "@markup.underline" })
hi(0, "@text.uri", { link = "@markup.link.url" })
hi(0, "@text.warning", { link = "@comment.warning" })
hi(0, "@textReference", { fg = "#e08762" })
hi(0, "@type", { fg = "#00ceb0" })
hi(0, "@type.builtin", { fg = "#369ce9" })
hi(0, "@type.builtin.tsx", { link = "@type" })
hi(0, "@type.builtin.typescript", { link = "@type" })
hi(0, "@type.qualifier", { fg = "#369ce9" })
hi(0, "@variable", { fg = "#98dcff" })
hi(0, "@variable.builtin", { fg = "#369ce9" })
hi(0, "@variable.member", { fg = "#98dcff" })
hi(0, "@variable.parameter", { fg = "#98dcff" })
hi(0, "@variable.parameter.builtin", { link = "Special" })
hi(0, "@variable.parameter.reference", { fg = "#98dcff" })
hi(0, "Added", { ctermfg = 10, fg = "#a0fcb4" })
hi(0, "BlinkCmpDoc", { link = "NormalFloat" })
hi(0, "BlinkCmpDocBorder", { link = "FloatBorder" })
hi(0, "BlinkCmpDocCursorLine", { link = "Visual" })
hi(0, "BlinkCmpDocSeparator", { link = "NormalFloat" })
hi(0, "BlinkCmpGhostText", { fg = "#707070" })
hi(0, "BlinkCmpKind", { fg = "#bbbbbb" })
hi(0, "BlinkCmpKindClass", { link = "BlinkCmpKindConstructor" })
hi(0, "BlinkCmpKindColor", { link = "cssColor" })
hi(0, "BlinkCmpKindConstant", { link = "@constant" })
hi(0, "BlinkCmpKindConstructor", { fg = "#f78800" })
hi(0, "BlinkCmpKindCopilot", { fg = "#00ceb0" })
hi(0, "BlinkCmpKindEnum", { link = "BlinkCmpKindConstructor" })
hi(0, "BlinkCmpKindEnumMember", { link = "@variable.member" })
hi(0, "BlinkCmpKindEvent", { fg = "#ffd601" })
hi(0, "BlinkCmpKindField", { link = "@variable.member" })
hi(0, "BlinkCmpKindFile", { link = "@text.uri" })
hi(0, "BlinkCmpKindFolder", { link = "NeotestDir" })
hi(0, "BlinkCmpKindFunction", { fg = "#d873d2" })
hi(0, "BlinkCmpKindInterface", { fg = "#98dcff" })
hi(0, "BlinkCmpKindKeyword", { fg = "#ffd601" })
hi(0, "BlinkCmpKindMethod", { fg = "#d873d2" })
hi(0, "BlinkCmpKindModule", { link = "BlinkCmpKindClass" })
hi(0, "BlinkCmpKindOperator", { link = "@operator" })
hi(0, "BlinkCmpKindProperty", { link = "BlinkCmpKindField" })
hi(0, "BlinkCmpKindReference", { link = "@variable.parameter.reference" })
hi(0, "BlinkCmpKindSnippet", { fg = "#ffd601" })
hi(0, "BlinkCmpKindStruct", { link = "@structure" })
hi(0, "BlinkCmpKindText", { fg = "#bbbbbb" })
hi(0, "BlinkCmpKindTypeParameter", { link = "@variable.parameter" })
hi(0, "BlinkCmpKindUnit", { link = "BlinkCmpKindField" })
hi(0, "BlinkCmpKindValue", { link = "@variable.member" })
hi(0, "BlinkCmpKindVariable", { link = "@variable.member" })
hi(0, "BlinkCmpLabel", { fg = "#d4d4d4" })
hi(0, "BlinkCmpLabelDescription", { fg = "#bbbbbb" })
hi(0, "BlinkCmpLabelDetail", { fg = "#bbbbbb" })
hi(0, "BlinkCmpLabelMatch", { bold = true, fg = "#14a2ff" })
hi(0, "BlinkCmpMenu", { link = "Pmenu" })
hi(0, "BlinkCmpMenuBorder", { link = "FloatBorder" })
hi(0, "BlinkCmpMenuSelection", { link = "PmenuSel" })
hi(0, "BlinkCmpScrollBarGutter", { link = "PmenuSbar" })
hi(0, "BlinkCmpScrollBarThumb", { link = "PmenuThumb" })
hi(0, "BlinkCmpSignatureHelp", { link = "NormalFloat" })
hi(0, "BlinkCmpSignatureHelpActiveParameter", { link = "LspSignatureActiveParameter" })
hi(0, "BlinkCmpSignatureHelpBorder", { link = "NormalFloat" })
hi(0, "BlinkCmpSource", { fg = "#bbbbbb" })
hi(0, "Boolean", { fg = "#369ce9" })
hi(0, "BufferCurrent", { bg = "#1f1f1f", fg = "#d4d4d4" })
hi(0, "BufferCurrentIndex", { bg = "#1f1f1f", fg = "#d4d4d4" })
hi(0, "BufferCurrentMod", { bg = "#1f1f1f", fg = "#e0b85e" })
hi(0, "BufferCurrentSign", { bg = "#1f1f1f", fg = "#d4d4d4" })
hi(0, "BufferCurrentTarget", { bg = "#1f1f1f", fg = "#ff2b38" })
hi(0, "BufferInactive", { bg = "#2d2d2d", fg = "#808080" })
hi(0, "BufferInactiveIndex", { bg = "#2d2d2d", fg = "#808080" })
hi(0, "BufferInactiveMod", { bg = "#2d2d2d", fg = "#e0b85e" })
hi(0, "BufferInactiveSign", { bg = "#2d2d2d", fg = "#808080" })
hi(0, "BufferInactiveTarget", { bg = "#2d2d2d", fg = "#ff2b38" })
hi(0, "BufferLineIndicatorSelected", { fg = "#242334" })
hi(0, "BufferTabpage", { bg = "#2d2d2d", fg = "#d4d4d4" })
hi(0, "BufferTabpageFill", { bg = "#2d2d2d", fg = "#d4d4d4" })
hi(0, "BufferTabpages", { bg = "#2d2d2d", fg = "#d4d4d4" })
hi(0, "BufferTabpagesFill", { bg = "#2d2d2d", fg = "#d4d4d4" })
hi(0, "BufferVisible", { bg = "#1f1f1f", fg = "#808080" })
hi(0, "BufferVisibleIndex", { bg = "#1f1f1f", fg = "#808080" })
hi(0, "BufferVisibleMod", { bg = "#1f1f1f", fg = "#e0b85e" })
hi(0, "BufferVisibleSign", { bg = "#1f1f1f", fg = "#808080" })
hi(0, "BufferVisibleTarget", { bg = "#1f1f1f", fg = "#ff2b38" })
hi(0, "Changed", { ctermfg = 14, fg = "#65fdfd" })
hi(0, "Character", { fg = "#e08762" })
hi(0, "CmpItemAbbr", { fg = "#d4d4d4" })
hi(0, "CmpItemAbbrDeprecated", { bg = "#202020", fg = "#584e44", strikethrough = true })
hi(0, "CmpItemAbbrMatch", { bold = true, fg = "#14a2ff" })
hi(0, "CmpItemAbbrMatchFuzzy", { bold = true, fg = "#14a2ff" })
hi(0, "CmpItemKind", { link = "Pmenu" })
hi(0, "CmpItemKindClass", { link = "CmpItemKindConstructor" })
hi(0, "CmpItemKindColor", { link = "cssColor" })
hi(0, "CmpItemKindConstant", { link = "@constant" })
hi(0, "CmpItemKindConstructor", { fg = "#f78800" })
hi(0, "CmpItemKindEnum", { link = "@variable.member" })
hi(0, "CmpItemKindEnumMember", { link = "@variable.member" })
hi(0, "CmpItemKindEvent", { link = "@constant" })
hi(0, "CmpItemKindField", { link = "@variable.member" })
hi(0, "CmpItemKindFile", { link = "@text.uri" })
hi(0, "CmpItemKindFolder", { link = "@text.uri" })
hi(0, "CmpItemKindFunction", { fg = "#d873d2" })
hi(0, "CmpItemKindInterface", { fg = "#98dcff" })
hi(0, "CmpItemKindKeyword", { fg = "#d4d4d4" })
hi(0, "CmpItemKindMethod", { fg = "#d873d2" })
hi(0, "CmpItemKindModule", { link = "CmpItemKindKeyword" })
hi(0, "CmpItemKindOperator", { link = "@operator" })
hi(0, "CmpItemKindProperty", { fg = "#d4d4d4" })
hi(0, "CmpItemKindReference", { link = "@variable.parameter.reference" })
hi(0, "CmpItemKindSnippet", { link = "@text" })
hi(0, "CmpItemKindStruct", { link = "@structure" })
hi(0, "CmpItemKindText", { fg = "#98dcff" })
hi(0, "CmpItemKindTypeParameter", { link = "@variable.parameter" })
hi(0, "CmpItemKindUnit", { fg = "#d4d4d4" })
hi(0, "CmpItemKindValue", { link = "@variable.member" })
hi(0, "CmpItemKindVariable", { fg = "#98dcff" })
hi(0, "CmpItemMenu", { fg = "#bbbbbb" })
hi(0, "CocHighlightRead", { bg = "#343b41" })
hi(0, "CocHighlightText", { bg = "#343b41" })
hi(0, "CocHighlightWrite", { bg = "#343b41" })
hi(0, "ColorColumn", { bg = "#222222" })
hi(0, "Comment", { fg = "#5d9d3c", italic = true })
hi(0, "CompeDocumentation", { link = "Pmenu" })
hi(0, "CompeDocumentationBorder", { link = "Pmenu" })
hi(0, "CompileModeCheckResult", { bold = true, fg = "#ff965f" })
hi(0, "CompileModeCheckTarget", { fg = "#ff965f" })
hi(0, "CompileModeCommandOutput", { fg = "#6298ff" })
hi(0, "CompileModeDirectoryMessage", { fg = "#6298ff" })
hi(0, "CompileModeError", { fg = "#ff2b38" })
hi(0, "CompileModeErrorLocus", { link = "Visual" })
hi(0, "CompileModeInfo", { fg = "#5d9d3c" })
hi(0, "CompileModeMessage", { underline = true })
hi(0, "CompileModeMessageCol", { fg = "#00ceb0" })
hi(0, "CompileModeMessageRow", { fg = "#d873d2" })
hi(0, "CompileModeOutputFile", { fg = "#a155e5" })
hi(0, "CompileModeWarning", { fg = yellow })
hi(0, "Conceal", { fg = "#d4d4d4" })
hi(0, "Conditional", { fg = "#d873d2" })
hi(0, "Constant", { fg = "#369ce9" })
hi(0, "CopilotSuggestion", { fg = "#6a6a6a" })
hi(0, "CurSearch", { bg = "#fce094", ctermbg = 11, ctermfg = 0, fg = "#060714" })
hi(0, "Cursor", { bg = "#b5cea8", bold = true, fg = "#163e5d" })
hi(0, "CursorColumn", { bg = "#222222" })
hi(0, "CursorLine", { bg = "#222222" })
hi(0, "CursorLineNr", { fg = "#bbbbbb" })
hi(0, "DapUIBreakpointsCurrentLine", { bold = true, fg = "#00ceb0" })
hi(0, "DapUIBreakpointsDisabledLine", { fg = "#584e44" })
hi(0, "DapUIBreakpointsInfo", { fg = "#00ceb0" })
hi(0, "DapUIBreakpointsLine", { fg = "#d873d2" })
hi(0, "DapUIBreakpointsPath", { fg = "#d873d2" })
hi(0, "DapUICurrentFrameName", { bold = true, fg = "#00ceb0" })
hi(0, "DapUIDecoration", { fg = "#d873d2" })
hi(0, "DapUIFloatBorder", { fg = "#d873d2" })
hi(0, "DapUILineNumber", { fg = "#d873d2" })
hi(0, "DapUIModifiedValue", { bold = true, fg = "#d873d2" })
hi(0, "DapUIPlayPause", { fg = "#00ceb0" })
hi(0, "DapUIPlayPauseNC", { fg = "#00ceb0" })
hi(0, "DapUIRestart", { fg = "#00ceb0" })
hi(0, "DapUIRestartNC", { fg = "#00ceb0" })
hi(0, "DapUIScope", { fg = "#d873d2" })
hi(0, "DapUISource", { fg = "#14a2ff" })
hi(0, "DapUIStepBack", { fg = "#d873d2" })
hi(0, "DapUIStepBackNC", { fg = "#d873d2" })
hi(0, "DapUIStepInto", { fg = "#d873d2" })
hi(0, "DapUIStepIntoNC", { fg = "#d873d2" })
hi(0, "DapUIStepOut", { fg = "#d873d2" })
hi(0, "DapUIStepOutNC", { fg = "#d873d2" })
hi(0, "DapUIStepOver", { fg = "#d873d2" })
hi(0, "DapUIStepOverNC", { fg = "#d873d2" })
hi(0, "DapUIStop", { fg = "#ff2b38" })
hi(0, "DapUIStopNC", { fg = "#ff2b38" })
hi(0, "DapUIStoppedThread", { fg = "#d873d2" })
hi(0, "DapUIThread", { fg = "#00ceb0" })
hi(0, "DapUIType", { fg = "#d873d2" })
hi(0, "DapUIUnavailable", { fg = "#584e44" })
hi(0, "DapUIUnavailableNC", { fg = "#584e44" })
hi(0, "DapUIWatchesEmpty", { fg = "#584e44" })
hi(0, "DapUIWatchesError", { fg = "#ff2b38" })
hi(0, "DapUIWatchesValue", { fg = "#00ceb0" })
hi(0, "DapUIWinSelect", { bold = true, fg = "#d873d2" })
hi(0, "DashboardDesc", { fg = "#e0b85e" })
hi(0, "DashboardFooter", { fg = "#369ce9", italic = true })
hi(0, "DashboardHeader", { fg = "#369ce9" })
hi(0, "DashboardIcon", { fg = "#e0b85e" })
hi(0, "DashboardShortCut", { fg = "#d873d2" })
hi(0, "Debug", { fg = "#d4d4d4" })
hi(0, "Define", { fg = "#d873d2" })
hi(0, "Delimiter", { fg = "#d4d4d4" })
hi(0, "DiagnosticError", { fg = "#ff2b38" })
hi(0, "DiagnosticHint", { fg = "#369ce9" })
hi(0, "DiagnosticInfo", { fg = "#369ce9" })
hi(0, "DiagnosticOk", { fg = "#00ceb0" })
hi(0, "DiagnosticUnderlineError", { sp = "#f44747", undercurl = true })
hi(0, "DiagnosticUnderlineHint", { sp = "#569cd6", undercurl = true })
hi(0, "DiagnosticUnderlineInfo", { sp = "#569cd6", undercurl = true })
hi(0, "DiagnosticUnderlineWarn", { sp = "#dcdcaa", undercurl = true })
hi(0, "DiagnosticUnnecessary", { fg = "#5ca0c0" })
hi(0, "DiagnosticWarn", { fg = yellow })
hi(0, "DiffAdd", { bg = "#4b5632" })
hi(0, "DiffChange", { bg = "#4b1818" })
hi(0, "DiffDelete", { bg = "#6f1313" })
hi(0, "DiffText", { bg = "#6f1313" })
hi(0, "Directory", { fg = "#369ce9" })
hi(0, "EndOfBuffer", {})
hi(0, "Error", { fg = "#ff2b38", sp = "#f44747", undercurl = true })
hi(0, "ErrorMsg", { fg = "#ff2b38" })
hi(0, "Exception", { fg = "#d873d2" })
hi(0, "Float", { fg = "#a7d58e" })
hi(0, "FocusedSymbol", { bg = "#084671", fg = "#ffffff" })
hi(0, "FoldColumn", { fg = "#ffffff" })
hi(0, "Folded", { bg = "#202d39" })
hi(0, "Function", { fg = yellow })
hi(0, "GitGutterAdd", { fg = "#5d9d3c" })
hi(0, "GitGutterChange", { fg = yellow })
hi(0, "GitGutterDelete", { fg = "#ff2b38" })
hi(0, "GitSignsAdd", { fg = "#5d9d3c" })
hi(0, "GitSignsAddLn", { bg = "#6a9955" })
hi(0, "GitSignsChange", { fg = yellow })
hi(0, "GitSignsChangeLn", { bg = "#dcdcaa" })
hi(0, "GitSignsDelete", { fg = "#ff2b38" })
hi(0, "GitSignsDeleteLn", { bg = "#f44747" })
hi(0, "GitSignsStagedAdd", { fg = "#2e4e1d" })
hi(0, "GitSignsStagedAddCul", { fg = "#2e4e1d" })
hi(0, "GitSignsStagedAddLn", { bg = "#6a9955" })
hi(0, "GitSignsStagedAddNr", { fg = "#2e4e1d" })
hi(0, "GitSignsStagedChange", { fg = "#6f6f45" })
hi(0, "GitSignsStagedChangeCul", { fg = "#6f6f45" })
hi(0, "GitSignsStagedChangeLn", { bg = "#dcdcaa" })
hi(0, "GitSignsStagedChangeNr", { fg = "#6f6f45" })
hi(0, "GitSignsStagedChangedelete", { fg = "#6f6f45" })
hi(0, "GitSignsStagedChangedeleteCul", { fg = "#6f6f45" })
hi(0, "GitSignsStagedChangedeleteLn", { bg = "#dcdcaa" })
hi(0, "GitSignsStagedChangedeleteNr", { fg = "#6f6f45" })
hi(0, "GitSignsStagedDelete", { fg = "#850a16" })
hi(0, "GitSignsStagedDeleteCul", { fg = "#850a16" })
hi(0, "GitSignsStagedDeleteNr", { fg = "#850a16" })
hi(0, "GitSignsStagedTopdelete", { fg = "#850a16" })
hi(0, "GitSignsStagedTopdeleteCul", { fg = "#850a16" })
hi(0, "GitSignsStagedTopdeleteLn", { bg = "#f44747" })
hi(0, "GitSignsStagedTopdeleteNr", { fg = "#850a16" })
hi(0, "GitSignsStagedUntracked", { fg = "#2e4e1d" })
hi(0, "GitSignsStagedUntrackedCul", { fg = "#2e4e1d" })
hi(0, "GitSignsStagedUntrackedLn", { bg = "#6a9955" })
hi(0, "GitSignsStagedUntrackedNr", { fg = "#2e4e1d" })
hi(0, "IblIndent", { fg = "#404040", nocombine = true })
hi(0, "IblScope", { fg = "#707070", nocombine = true })
hi(0, "IblWhitespace", { fg = "#404040", nocombine = true })
hi(0, "Identifier", { fg = "#98dcff" })
hi(0, "Ignore", { fg = "#d4d4d4" })
hi(0, "IlluminatedWordRead", { bg = "#343b41" })
hi(0, "IlluminatedWordText", { bg = "#343b41" })
hi(0, "IlluminatedWordWrite", { bg = "#343b41" })
hi(0, "IncSearch", { bg = "#515c6a" })
hi(0, "Include", { fg = "#d873d2" })
hi(0, "Keyword", { fg = "#d873d2" })
hi(0, "LSPSagaDiagnosticTruncateLine", { fg = "#ffffff" })
hi(0, "Label", { fg = "#d873d2" })
hi(0, "LineNr", { fg = "#ffffff" })
hi(0, "LspFloatWinBorder", { fg = "#ffffff" })
hi(0, "LspFloatWinNormal", { fg = "#d4d4d4" })
hi(0, "LspInfoBorder", { fg = "#ffffff" })
hi(0, "LspLinesDiagBorder", { fg = "#ffffff" })
hi(0, "LspReferenceRead", { bg = "#343b41" })
hi(0, "LspReferenceText", { bg = "#343b41" })
hi(0, "LspReferenceWrite", { bg = "#343b41" })
hi(0, "LspSagaBorderTitle", { fg = "#584e44" })
hi(0, "LspSagaCodeActionBorder", { fg = "#ffffff" })
hi(0, "LspSagaDefPreviewBorder", { fg = "#ffffff" })
hi(0, "LspSagaDiagnosticBorder", { fg = "#ffffff" })
hi(0, "LspSagaDocTruncateLine", { fg = "#ffffff" })
hi(0, "LspSagaHoverBorder", { fg = "#ffffff" })
hi(0, "LspSagaLspFinderBorder", { fg = "#ffffff" })
hi(0, "LspSagaRenameBorder", { fg = "#ffffff" })
hi(0, "LspSagaShTruncateLine", { fg = "#ffffff" })
hi(0, "LspSagaSignatureHelpBorder", { fg = "#ffffff" })
hi(0, "Macro", { fg = "#d873d2" })
hi(0, "MatchParen", { bg = "#51504f" })
hi(0, "MiniIconsAzure", { fg = "#369ce9" })
hi(0, "MiniIconsBlue", { fg = "#14a2ff" })
hi(0, "MiniIconsCyan", { fg = "#00ceb0" })
hi(0, "MiniIconsGreen", { fg = "#5d9d3c" })
hi(0, "MiniIconsGrey", { fg = "#d4d4d4" })
hi(0, "MiniIconsOrange", { fg = "#ff2b38" })
hi(0, "MiniIconsPurple", { fg = "#d873d2" })
hi(0, "MiniIconsRed", { fg = "#ff2b38" })
hi(0, "MiniIconsYellow", { fg = "#ffd601" })
hi(0, "MiniStatuslineDevinfo", { bg = "#636369" })
hi(0, "MiniStatuslineFileinfo", { bg = "#636369" })
hi(0, "MiniStatuslineFilename", { bg = "#373737", fg = "#d4d4d4" })
hi(0, "MiniStatuslineInactive", { bg = "#252526", fg = "#d4d4d4" })
hi(0, "MiniStatuslineModeCommand", { bg = "#d16969", bold = true })
hi(0, "MiniStatuslineModeInsert", { bg = "#9cdcfe", bold = true })
hi(0, "MiniStatuslineModeNormal", { bg = "#b5cea8", bold = true })
hi(0, "MiniStatuslineModeOther", { bg = "#252526", fg = "#d4d4d4" })
hi(0, "MiniStatuslineModeReplace", { bg = "#d7ba7d", bold = true })
hi(0, "MiniStatuslineModeVisual", { bg = "#c586c0", bold = true })
hi(0, "ModeMsg", { bg = "#252526", fg = "#d4d4d4" })
hi(0, "MoreMsg", { bg = "#252526", fg = "#d4d4d4" })
hi(0, "NeoTreeBufferNumber", { fg = "#ffffff" })
hi(0, "NeoTreeCursorLine", { bg = "#222222" })
hi(0, "NeoTreeDimText", { bg = "#222222" })
hi(0, "NeoTreeDirectoryIcon", { fg = "#369ce9" })
hi(0, "NeoTreeDirectoryName", { fg = "#d4d4d4" })
hi(0, "NeoTreeDotfile", { fg = "#5ca0c0" })
hi(0, "NeoTreeFileIcon", { fg = "#605fb3" })
hi(0, "NeoTreeFileName", { fg = "#d4d4d4" })
hi(0, "NeoTreeFileNameOpened", { bg = "#222222", fg = "#d4d4d4" })
hi(0, "NeoTreeFilterTerm", { fg = "#d4d4d4" })
hi(0, "NeoTreeFloatBorder", { fg = "#ffffff" })
hi(0, "NeoTreeFloatTitle", { fg = "#ffffff" })
hi(0, "NeoTreeTitleBar", { fg = "#ffffff" })
hi(0, "NeogitDiffAdd", { bg = "#373d29", fg = "#69bf7c" })
hi(0, "NeogitDiffAddCursor", { link = "NeogitDiffAddHighlight" })
hi(0, "NeogitDiffAddHighlight", { bg = "#4b5632", fg = "#69bf7c" })
hi(0, "NeogitDiffContext", { bg = "#252526", fg = "#bbbbbb" })
hi(0, "NeogitDiffContextCursor", { link = "NeogitDiffContextHighlight" })
hi(0, "NeogitDiffContextHighlight", { bg = "#373737", fg = "#bbbbbb" })
hi(0, "NeogitDiffDelete", { bg = "#4b1818", fg = "#d8361a" })
hi(0, "NeogitDiffDeleteCursor", { link = "NeogitDiffDeleteHighlight" })
hi(0, "NeogitDiffDeleteHighlight", { bg = "#6f1313", fg = "#d8361a" })
hi(0, "NeogitDiffHeader", { fg = "#898989" })
hi(0, "NeogitDiffHeaderHighlight", { fg = "#898989" })
hi(0, "NeogitHunkHeader", { bg = "#252526", fg = "#eebd70" })
hi(0, "NeogitHunkHeaderCursor", { link = "NeogitHunkHeaderHighlight" })
hi(0, "NeogitHunkHeaderHighlight", { bg = "#373737", fg = "#eebd70" })
hi(0, "NeogitWinSeparator", { link = "WinSeparator" })
hi(0, "NeotestAdapterName", { bold = true, fg = "#d4d4d4" })
hi(0, "NeotestDir", { fg = "#369ce9" })
hi(0, "NeotestExpandMarker", { fg = "#584e44" })
hi(0, "NeotestFailed", { fg = "#ff2b38" })
hi(0, "NeotestFile", { fg = "#369ce9" })
hi(0, "NeotestFocused", { bold = true })
hi(0, "NeotestIndent", { fg = "#584e44" })
hi(0, "NeotestMarked", { bold = true, fg = "#e0b85e" })
hi(0, "NeotestNamespace", { fg = "#d873d2" })
hi(0, "NeotestPassed", { fg = "#00ceb0" })
hi(0, "NeotestRunning", { fg = "#ffd601" })
hi(0, "NeotestSkipped", { fg = "#369ce9" })
hi(0, "NeotestTarget", { fg = "#e6545a" })
hi(0, "NeotestWatching", { fg = "#ffd601" })
hi(0, "NeotestWinSelect", { bold = true, fg = "#369ce9" })
hi(0, "NoiceFormatProgressDone", { bg = "#613315" })
hi(0, "NoiceHiddenCursor", { blend = 100, nocombine = true })
hi(0, "NonText", { fg = "#ffffff" })
hi(0, "Normal", { fg = "#d4d4d4" })
hi(0, "NormalFloat", { bg = "#202020" })
hi(0, "Number", { fg = "#a7d58e" })
hi(0, "NvimTreeCursorLine", { bg = "#222222" })
hi(0, "NvimTreeEmptyFolderName", { fg = "#808080" })
hi(0, "NvimTreeEndOfBuffer", { fg = "#222222" })
hi(0, "NvimTreeFolderIcon", { fg = "#369ce9" })
hi(0, "NvimTreeFolderName", { fg = "#d4d4d4" })
hi(0, "NvimTreeGitDeleted", { fg = "#d8361a" })
hi(0, "NvimTreeGitDirty", { fg = "#eebd70" })
hi(0, "NvimTreeGitIgnored", { fg = "#8c8c8c" })
hi(0, "NvimTreeGitMerge", { fg = "#52cf85" })
hi(0, "NvimTreeGitNew", { fg = "#69bf7c" })
hi(0, "NvimTreeGitRenamed", { fg = "#52cf85" })
hi(0, "NvimTreeGitStaged", { fg = "#eebd70" })
hi(0, "NvimTreeImageFile", { fg = "#605fb3" })
hi(0, "NvimTreeIndentMarker", { fg = "#ffffff" })
hi(0, "NvimTreeNormal", { fg = "#d4d4d4" })
hi(0, "NvimTreeOpenedFolderName", { bg = "#222222" })
hi(0, "NvimTreeRootFolder", { bold = true, fg = "#d4d4d4" })
hi(0, "NvimTreeSpecialFile", { fg = "#d873d2", underline = true })
hi(0, "NvimTreeVertSplit", { fg = "#444444" })
hi(0, "Operator", { fg = "#d4d4d4" })
hi(0, "Pmenu", { bg = "#202020", fg = "#bbbbbb" })
hi(0, "PmenuSbar", { bg = "#343b41" })
hi(0, "PmenuSel", { bg = "#04395e", fg = "#bbbbbb" })
hi(0, "PmenuThumb", { bg = "#bbbbbb" })
hi(0, "PreProc", { fg = "#d873d2" })
hi(0, "Question", { fg = "#369ce9" })
hi(0, "QuickFixLine", { bold = true })
hi(0, "RainbowDelimiterBlue", { fg = "#14a2ff" })
hi(0, "RainbowDelimiterCyan", { fg = "#00ceb0" })
hi(0, "RainbowDelimiterGreen", { fg = "#5d9d3c" })
hi(0, "RainbowDelimiterOrange", { fg = "#e08762" })
hi(0, "RainbowDelimiterRed", { fg = "#d873d2" })
hi(0, "RainbowDelimiterViolet", { fg = "#605fb3" })
hi(0, "RainbowDelimiterYellow", { fg = "#e0b85e" })
hi(0, "Removed", { ctermfg = 9, fg = "#ffbbb2" })
hi(0, "RenderMarkdownH1", { bold = true, fg = "#369ce9" })
hi(0, "RenderMarkdownH1Bg", { bg = "#343b41", bold = true })
hi(0, "RenderMarkdownH2", { bold = true, fg = "#e08762" })
hi(0, "RenderMarkdownH2Bg", { bg = "#343b41", bold = true })
hi(0, "RenderMarkdownH3", { bold = true, fg = yellow })
hi(0, "RenderMarkdownH3Bg", { bg = "#343b41", bold = true })
hi(0, "RenderMarkdownH4", { bold = true, fg = "#5d9d3c" })
hi(0, "RenderMarkdownH4Bg", { bg = "#343b41", bold = true })
hi(0, "RenderMarkdownH5", { bold = true, fg = "#369ce9" })
hi(0, "RenderMarkdownH5Bg", { bg = "#343b41", bold = true })
hi(0, "RenderMarkdownH6", { bold = true, fg = "#d873d2" })
hi(0, "RenderMarkdownH6Bg", { bg = "#343b41", bold = true })
hi(0, "Repeat", { fg = "#d873d2" })
hi(0, "Search", { bg = "#613315" })
hi(0, "SignColumn", {})
hi(0, "SnacksBackdrop", { bg = "#000000" })
hi(0, "SnacksImageMath", { fg = "#e0b85e" })
hi(0, "SnacksIndent", { fg = "#404040", nocombine = true })
hi(0, "SnacksPicker", { link = "Normal" })
hi(0, "SnacksPickerBorder", { link = "Normal" })
hi(0, "SnacksPickerDir", { nocombine = true })
hi(0, "SnacksPickerDirectory", { nocombine = true })
hi(0, "SnacksPickerListCursorLine", { link = "PmenuSel" })
hi(0, "SnacksPickerPreviewCursorLine", { nocombine = true })
hi(0, "Special", { fg = "#e0b85e" })
hi(0, "SpecialChar", { fg = "#d4d4d4" })
hi(0, "SpecialComment", { fg = "#5d9d3c" })
hi(0, "SpecialKey", { fg = "#369ce9" })
hi(0, "SpellBad", { sp = "#f44747", undercurl = true })
hi(0, "SpellCap", { sp = "#dcdcaa", undercurl = true })
hi(0, "SpellLocal", { sp = "#569cd6", undercurl = true })
hi(0, "SpellRare", { sp = "#646695", undercurl = true })
hi(0, "Statement", { fg = "#d873d2" })
hi(0, "StatusLine", { bg = "#373737", fg = "#d4d4d4" })
hi(0, "StatusLineNC", { fg = "#d4d4d4" })
hi(0, "StorageClass", { fg = "#369ce9" })
hi(0, "String", { fg = "#e08762" })
hi(0, "Structure", { fg = "#00ceb0" })
hi(0, "SymbolsOutlineConnector", { fg = "#ffffff" })
hi(0, "TabLine", { bg = "#2d2d2d", fg = "#d4d4d4" })
hi(0, "TabLineFill", { bg = "#252526", fg = "#d4d4d4" })
hi(0, "TabLineSel", { bg = "#1f1f1f", fg = "#d4d4d4" })
hi(0, "Tag", { fg = "#d4d4d4" })
hi(0, "TelescopeMatching", { bold = true, fg = "#14a2ff" })
hi(0, "TelescopeMultiSelection", { bg = "#04395e", fg = "#d4d4d4" })
hi(0, "TelescopeNormal", { fg = "#d4d4d4" })
hi(0, "TelescopePreviewBorder", { fg = "#ffffff" })
hi(0, "TelescopePromptBorder", { fg = "#ffffff" })
hi(0, "TelescopePromptPrefix", { fg = "#d4d4d4" })
hi(0, "TelescopeResultsBorder", { fg = "#ffffff" })
hi(0, "TelescopeSelection", { bg = "#04395e", fg = "#d4d4d4" })
hi(0, "Title", { bold = true })
hi(0, "Todo", { bold = true, fg = "#e0b85e" })
hi(0, "TodoBgFIX", { bg = "#f44747", bold = true, fg = "#000000" })
hi(0, "TodoBgHACK", { bg = "#dcdcaa", bold = true, fg = "#000000" })
hi(0, "TodoBgNOTE", { bg = "#569cd6", bold = true, fg = "#000000" })
hi(0, "TodoBgPERF", { bg = "#9cdcfe", bold = true, fg = "#000000" })
hi(0, "TodoBgTEST", { bg = "#9cdcfe", bold = true, fg = "#000000" })
hi(0, "TodoBgTODO", { bg = "#569cd6", bold = true, fg = "#000000" })
hi(0, "TodoBgWARN", { bg = "#dcdcaa", bold = true, fg = "#000000" })
hi(0, "TodoFgFIX", { fg = "#ff2b38" })
hi(0, "TodoFgHACK", { fg = yellow })
hi(0, "TodoFgNOTE", { fg = "#369ce9" })
hi(0, "TodoFgPERF", { fg = "#98dcff" })
hi(0, "TodoFgTEST", { fg = "#98dcff" })
hi(0, "TodoFgTODO", { fg = "#369ce9" })
hi(0, "TodoFgWARN", { fg = yellow })
hi(0, "TodoSignFIX", { fg = "#ff2b38" })
hi(0, "TodoSignHACK", { fg = yellow })
hi(0, "TodoSignNOTE", { fg = "#369ce9" })
hi(0, "TodoSignPERF", { fg = "#98dcff" })
hi(0, "TodoSignTEST", { fg = "#98dcff" })
hi(0, "TodoSignTODO", { fg = "#369ce9" })
hi(0, "TodoSignWARN", { fg = yellow })
hi(0, "TroubleNormal", { link = "Normal" })
hi(0, "TroubleNormalNC", { link = "Normal" })
hi(0, "Type", { fg = "#369ce9" })
hi(0, "Typedef", { fg = "#369ce9" })
hi(0, "VertSplit", { fg = "#444444" })
hi(0, "Visual", { bg = "#264f78" })
hi(0, "VisualNOS", { bg = "#264f78" })
hi(0, "WarningMsg", { fg = yellow })
hi(0, "WhichKeyBorder", { fg = "#ffffff" })
hi(0, "WhichKeyIconAzure", { fg = "#00ceb0" })
hi(0, "WhichKeyIconBlue", { fg = "#369ce9" })
hi(0, "WhichKeyIconCyan", { link = "MiniIconsCyan" })
hi(0, "WhichKeyIconGreen", { fg = "#5d9d3c" })
hi(0, "WhichKeyIconGrey", { fg = "#808080" })
hi(0, "WhichKeyIconOrange", { fg = "#e0b85e" })
hi(0, "WhichKeyIconPurple", { fg = "#d873d2" })
hi(0, "WhichKeyIconRed", { fg = "#ff2b38" })
hi(0, "WhichKeyIconYellow", { fg = yellow })
hi(0, "WhichKeySeparator", { link = "Normal" })
hi(0, "WhichKeyValue", { link = "Normal" })
hi(0, "Whitespace", { fg = "#ffffff" })
hi(0, "WildMenu", { bg = "#264f78" })
hi(0, "WinBar", { bold = true, fg = "#d4d4d4" })
hi(0, "WinBarNC", { fg = "#d4d4d4" })
hi(0, "WinSeparator", { link = "VertSplit" })
hi(0, "asciidocAdmonition", { fg = "#e08762" })
hi(0, "asciidocAttributeEntry", { fg = "#e0b85e" })
hi(0, "asciidocAttributeList", { fg = "#d873d2" })
hi(0, "asciidocAttributeRef", { fg = "#e0b85e" })
hi(0, "asciidocBackslash", { link = "Keyword" })
hi(0, "asciidocHLabel", { bold = true, fg = "#369ce9" })
hi(0, "asciidocListingBlock", { fg = "#e08762" })
hi(0, "asciidocMacro", { fg = "#d873d2" })
hi(0, "asciidocMacroAttributes", { fg = "#e0b85e" })
hi(0, "asciidocOneLineTitle", { bold = true, fg = "#369ce9" })
hi(0, "asciidocPassthroughBlock", { fg = "#369ce9" })
hi(0, "asciidocQuotedBold", { link = "markdownBold" })
hi(0, "asciidocQuotedEmphasized", { fg = "#369ce9", italic = true })
hi(0, "asciidocQuotedEmphasized2", { fg = "#369ce9", italic = true })
hi(0, "asciidocQuotedEmphasizedItalic", { fg = "#369ce9", italic = true })
hi(0, "asciidocQuotedMonospaced", { fg = "#e08762" })
hi(0, "asciidocQuotedMonospaced2", { link = "asciidocQuotedMonospaced" })
hi(0, "asciidocQuotedUnconstrainedBold", { link = "asciidocQuotedBold" })
hi(0, "asciidocQuotedUnconstrainedEmphasized", { link = "asciidocQuotedEmphasized" })
hi(0, "asciidocTriplePlusPassthrough", { fg = yellow })
hi(0, "asciidocURL", { link = "markdownUrl" })
hi(0, "cssAttr", { fg = "#e08762" })
hi(0, "cssAttrRegion", { fg = "#e08762" })
hi(0, "cssBraces", { fg = "#d4d4d4" })
hi(0, "cssClassName", { fg = "#e0b85e" })
hi(0, "cssColor", { fg = "#e08762" })
hi(0, "cssDefinition", { fg = "#98dcff" })
hi(0, "cssFunction", { fg = "#e08762" })
hi(0, "cssFunctionName", { fg = "#e08762" })
hi(0, "cssIdentifier", { fg = "#e0b85e" })
hi(0, "cssImportant", { fg = "#369ce9" })
hi(0, "cssInclude", { fg = "#d873d2" })
hi(0, "cssProp", { fg = "#98dcff" })
hi(0, "cssPseudoClass", { fg = "#e0b85e" })
hi(0, "cssPseudoClassId", { fg = "#e0b85e" })
hi(0, "cssPseudoClassLang", { fg = "#e0b85e" })
hi(0, "cssStyle", { fg = "#98dcff" })
hi(0, "cssTagName", { fg = "#e0b85e" })
hi(0, "cssUnitDecorators", { fg = "#e08762" })
hi(0, "cssValueLength", { fg = "#e08762" })
hi(0, "cssValueNumber", { fg = "#e08762" })
hi(0, "cssVendor", { fg = "#e08762" })
hi(0, "debugPC", { bg = "#4c4c19" })
hi(0, "diffAdded", { link = "DiffAdd" })
hi(0, "diffChanged", { link = "DiffChange" })
hi(0, "diffRemoved", { link = "DiffDelete" })
hi(0, "gitcommitBlank", { fg = "#d873d2" })
hi(0, "gitcommitBranch", { fg = "#d873d2" })
hi(0, "gitcommitComment", { fg = "#808080" })
hi(0, "gitcommitDiscardedFile", { fg = "#ff2b38" })
hi(0, "gitcommitDiscardedType", { fg = "#ff2b38" })
hi(0, "gitcommitHeader", { fg = "#808080" })
hi(0, "gitcommitOnBranch", { fg = "#808080" })
hi(0, "gitcommitOverflow", { fg = "#ff2b38" })
hi(0, "gitcommitSelectedFile", { fg = "#5d9d3c" })
hi(0, "gitcommitSelectedType", { fg = "#5d9d3c" })
hi(0, "gitcommitSummary", { fg = "#d873d2" })
hi(0, "goBoolean", { fg = "#369ce9" })
hi(0, "goBuiltins", { fg = yellow })
hi(0, "goComplexes", { fg = "#00ceb0" })
hi(0, "goConst", { fg = "#369ce9" })
hi(0, "goDeclType", { fg = "#369ce9" })
hi(0, "goDeclaration", { fg = "#369ce9" })
hi(0, "goFloats", { fg = "#00ceb0" })
hi(0, "goFunctionCall", { fg = yellow })
hi(0, "goImport", { fg = "#369ce9" })
hi(0, "goMethodCall", { fg = yellow })
hi(0, "goPackage", { fg = "#369ce9" })
hi(0, "goPredefinedIdentifiers", { fg = "#369ce9" })
hi(0, "goReceiver", { fg = "#d4d4d4" })
hi(0, "goReceiverType", { fg = "#d4d4d4" })
hi(0, "goSignedInts", { fg = "#00ceb0" })
hi(0, "goSingleDecl", { fg = "#98dcff" })
hi(0, "goStatement", { fg = "#d873d2" })
hi(0, "goTodo", { fg = "#5d9d3c" })
hi(0, "goType", { fg = "#00ceb0" })
hi(0, "goTypeDecl", { fg = "#369ce9" })
hi(0, "goTypeName", { fg = "#00ceb0" })
hi(0, "goUnsignedInts", { fg = "#00ceb0" })
hi(0, "goVar", { fg = "#369ce9" })
hi(0, "goVarAssign", { fg = "#98dcff" })
hi(0, "goVarDefs", { fg = "#98dcff" })
hi(0, "htmlArg", { fg = "#98dcff" })
hi(0, "htmlEndTag", { fg = "#808080" })
hi(0, "htmlSpecialTagName", { fg = "#369ce9" })
hi(0, "htmlTag", { fg = "#808080" })
hi(0, "htmlTagName", { fg = "#369ce9" })
hi(0, "illuminatedCurWord", { bg = "#343b41" })
hi(0, "illuminatedWord", { bg = "#343b41" })
hi(0, "jsClassDefinition", { fg = "#00ceb0" })
hi(0, "jsClassKeyword", { fg = "#369ce9" })
hi(0, "jsDestructuringBlock", { fg = "#98dcff" })
hi(0, "jsExportDefault", { fg = "#d873d2" })
hi(0, "jsExtendsKeyword", { fg = "#369ce9" })
hi(0, "jsFuncArgs", { fg = "#98dcff" })
hi(0, "jsFuncBlock", { fg = "#98dcff" })
hi(0, "jsFuncCall", { fg = yellow })
hi(0, "jsGlobalObjects", { fg = "#00ceb0" })
hi(0, "jsIfElseBlock", { fg = "#98dcff" })
hi(0, "jsModuleKeyword", { fg = "#98dcff" })
hi(0, "jsObjectKey", { fg = "#98dcff" })
hi(0, "jsObjectProp", { fg = "#98dcff" })
hi(0, "jsObjectValue", { fg = "#98dcff" })
hi(0, "jsOperatorKeyword", { fg = "#369ce9" })
hi(0, "jsParen", { fg = "#98dcff" })
hi(0, "jsParenIfElse", { fg = "#98dcff" })
hi(0, "jsRegexpString", { fg = "#e6545a" })
hi(0, "jsSpreadExpression", { fg = "#98dcff" })
hi(0, "jsSpreadOperator", { fg = "#98dcff" })
hi(0, "jsThis", { fg = "#369ce9" })
hi(0, "jsVariableDef", { fg = "#98dcff" })
hi(0, "jsonBoolean", { fg = "#369ce9" })
hi(0, "jsonEscape", { fg = "#e0b85e" })
hi(0, "jsonKeyword", { fg = "#98dcff" })
hi(0, "jsonNull", { fg = "#369ce9" })
hi(0, "lCursor", { bg = "#d4d4d4" })
hi(0, "luaBuiltIn", { fg = "#369ce9" })
hi(0, "luaFuncArgName", { fg = "#98dcff" })
hi(0, "luaFuncCall", { fg = yellow })
hi(0, "luaFuncKeyword", { fg = "#d873d2" })
hi(0, "luaLocal", { fg = "#d873d2" })
hi(0, "lualine_a_command", { bg = "#ddb6f2", bold = true, fg = "#262626", nocombine = true })
hi(0, "lualine_a_inactive", { bg = "#262626", bold = true, fg = "#ffffff", nocombine = true })
hi(0, "lualine_a_insert", { bg = "#4ec9b0", bold = true, fg = "#262626", nocombine = true })
hi(0, "lualine_a_normal", { bg = "#0a7aca", bold = true, fg = "#ffffff", nocombine = true })
hi(0, "lualine_a_replace", { bg = "#f44747", bold = true, fg = "#262626", nocombine = true })
hi(0, "lualine_a_terminal", { bg = "#4ec9b0", bold = true, fg = "#262626", nocombine = true })
hi(0, "lualine_a_visual", { bg = "#ffaf00", bold = true, fg = "#262626", nocombine = true })
hi(0, "lualine_b_command", { fg = "#e3b0fe", nocombine = true })
hi(0, "lualine_b_diagnostics_error_command", { fg = "#ff2b38", nocombine = true })
hi(0, "lualine_b_diagnostics_error_inactive", { fg = "#ff2b38", nocombine = true })
hi(0, "lualine_b_diagnostics_error_insert", { fg = "#ff2b38", nocombine = true })
hi(0, "lualine_b_diagnostics_error_normal", { fg = "#ff2b38", nocombine = true })
hi(0, "lualine_b_diagnostics_error_replace", { fg = "#ff2b38", nocombine = true })
hi(0, "lualine_b_diagnostics_error_terminal", { fg = "#ff2b38", nocombine = true })
hi(0, "lualine_b_diagnostics_error_visual", { fg = "#ff2b38", nocombine = true })
hi(0, "lualine_b_diagnostics_hint_command", { fg = "#369ce9", nocombine = true })
hi(0, "lualine_b_diagnostics_hint_inactive", { fg = "#369ce9", nocombine = true })
hi(0, "lualine_b_diagnostics_hint_insert", { fg = "#369ce9", nocombine = true })
hi(0, "lualine_b_diagnostics_hint_normal", { fg = "#369ce9", nocombine = true })
hi(0, "lualine_b_diagnostics_hint_replace", { fg = "#369ce9", nocombine = true })
hi(0, "lualine_b_diagnostics_hint_terminal", { fg = "#369ce9", nocombine = true })
hi(0, "lualine_b_diagnostics_hint_visual", { fg = "#369ce9", nocombine = true })
hi(0, "lualine_b_diagnostics_info_command", { fg = "#369ce9", nocombine = true })
hi(0, "lualine_b_diagnostics_info_inactive", { fg = "#369ce9", nocombine = true })
hi(0, "lualine_b_diagnostics_info_insert", { fg = "#369ce9", nocombine = true })
hi(0, "lualine_b_diagnostics_info_normal", { fg = "#369ce9", nocombine = true })
hi(0, "lualine_b_diagnostics_info_replace", { fg = "#369ce9", nocombine = true })
hi(0, "lualine_b_diagnostics_info_terminal", { fg = "#369ce9", nocombine = true })
hi(0, "lualine_b_diagnostics_info_visual", { fg = "#369ce9", nocombine = true })
hi(0, "lualine_b_diagnostics_warn_command", { fg = yellow, nocombine = true })
hi(0, "lualine_b_diagnostics_warn_inactive", { fg = yellow, nocombine = true })
hi(0, "lualine_b_diagnostics_warn_insert", { fg = yellow, nocombine = true })
hi(0, "lualine_b_diagnostics_warn_normal", { fg = yellow, nocombine = true })
hi(0, "lualine_b_diagnostics_warn_replace", { fg = yellow, nocombine = true })
hi(0, "lualine_b_diagnostics_warn_terminal", { fg = yellow, nocombine = true })
hi(0, "lualine_b_diagnostics_warn_visual", { fg = yellow, nocombine = true })
hi(0, "lualine_b_diff_added_command", { fg = "#5d9d3c", nocombine = true })
hi(0, "lualine_b_diff_added_inactive", { fg = "#5d9d3c", nocombine = true })
hi(0, "lualine_b_diff_added_insert", { fg = "#5d9d3c", nocombine = true })
hi(0, "lualine_b_diff_added_normal", { fg = "#5d9d3c", nocombine = true })
hi(0, "lualine_b_diff_added_replace", { fg = "#5d9d3c", nocombine = true })
hi(0, "lualine_b_diff_added_terminal", { fg = "#5d9d3c", nocombine = true })
hi(0, "lualine_b_diff_added_visual", { fg = "#5d9d3c", nocombine = true })
hi(0, "lualine_b_diff_modified_command", { fg = yellow, nocombine = true })
hi(0, "lualine_b_diff_modified_inactive", { fg = yellow, nocombine = true })
hi(0, "lualine_b_diff_modified_insert", { fg = yellow, nocombine = true })
hi(0, "lualine_b_diff_modified_normal", { fg = yellow, nocombine = true })
hi(0, "lualine_b_diff_modified_replace", { fg = yellow, nocombine = true })
hi(0, "lualine_b_diff_modified_terminal", { fg = yellow, nocombine = true })
hi(0, "lualine_b_diff_modified_visual", { fg = yellow, nocombine = true })
hi(0, "lualine_b_diff_removed_command", { fg = "#ff2b38", nocombine = true })
hi(0, "lualine_b_diff_removed_inactive", { fg = "#ff2b38", nocombine = true })
hi(0, "lualine_b_diff_removed_insert", { fg = "#ff2b38", nocombine = true })
hi(0, "lualine_b_diff_removed_normal", { fg = "#ff2b38", nocombine = true })
hi(0, "lualine_b_diff_removed_replace", { fg = "#ff2b38", nocombine = true })
hi(0, "lualine_b_diff_removed_terminal", { fg = "#ff2b38", nocombine = true })
hi(0, "lualine_b_diff_removed_visual", { fg = "#ff2b38", nocombine = true })
hi(0, "lualine_b_inactive", { fg = "#666666", nocombine = true })
hi(0, "lualine_b_insert", { fg = "#00ceb0", nocombine = true })
hi(0, "lualine_b_normal", { fg = "#007acc", nocombine = true })
hi(0, "lualine_b_replace", { fg = "#ff2b38", nocombine = true })
hi(0, "lualine_b_terminal", { fg = "#ffffff", nocombine = true })
hi(0, "lualine_b_visual", { fg = "#ffaf00", nocombine = true })
hi(0, "lualine_c_command", { fg = "#ffffff", nocombine = true })
hi(0, "lualine_c_inactive", { fg = "#666666", nocombine = true })
hi(0, "lualine_c_insert", { fg = "#ffffff", nocombine = true })
hi(0, "lualine_c_normal", { fg = "#ffffff", nocombine = true })
hi(0, "lualine_c_replace", { fg = "#ffffff", nocombine = true })
hi(0, "lualine_c_terminal", { fg = "#ffffff", nocombine = true })
hi(0, "lualine_transitional_lualine_a_command_to_lualine_b_command", { fg = "#e3b0fe", nocombine = true })
hi(0, "lualine_transitional_lualine_a_normal_to_lualine_b_normal", { fg = "#007acc", nocombine = true })
hi(0, "lualine_transparent", { fg = "#d4d4d4", nocombine = true })
hi(0, "lualine_x_filetype_DevIconDefault_command", { fg = "#5e838f", nocombine = true })
hi(0, "lualine_x_filetype_DevIconDefault_inactive", { fg = "#5e838f", nocombine = true })
hi(0, "lualine_x_filetype_DevIconDefault_insert", { fg = "#5e838f", nocombine = true })
hi(0, "lualine_x_filetype_DevIconDefault_normal", { fg = "#5e838f", nocombine = true })
hi(0, "lualine_x_filetype_DevIconDefault_replace", { fg = "#5e838f", nocombine = true })
hi(0, "lualine_x_filetype_DevIconDefault_terminal", { fg = "#5e838f", nocombine = true })
hi(0, "lualine_x_filetype_DevIconDefault_visual", { fg = "#5e838f", nocombine = true })
hi(0, "lualine_x_filetype_DevIconRb_command", { fg = "#77000c", nocombine = true })
hi(0, "lualine_x_filetype_DevIconRb_inactive", { fg = "#77000c", nocombine = true })
hi(0, "lualine_x_filetype_DevIconRb_insert", { fg = "#77000c", nocombine = true })
hi(0, "lualine_x_filetype_DevIconRb_normal", { fg = "#77000c", nocombine = true })
hi(0, "lualine_x_filetype_DevIconRb_replace", { fg = "#77000c", nocombine = true })
hi(0, "lualine_x_filetype_DevIconRb_terminal", { fg = "#77000c", nocombine = true })
hi(0, "lualine_x_filetype_DevIconRb_visual", { fg = "#77000c", nocombine = true })
hi(0, "markdownBold", { bold = true, fg = "#369ce9" })
hi(0, "markdownCode", { fg = "#e08762" })
hi(0, "markdownCodeDelimiter", { fg = "#d4d4d4" })
hi(0, "markdownEscape", { fg = "#e08762" })
hi(0, "markdownFootnote", { fg = "#e08762" })
hi(0, "markdownFootnoteDefinition", { fg = "#e08762" })
hi(0, "markdownHeadingDelimiter", { fg = "#369ce9" })
hi(0, "markdownLinkText", { fg = "#e08762" })
hi(0, "markdownRule", { bold = true, fg = "#369ce9" })
hi(0, "markdownUrl", { fg = "#d4d4d4", underline = true })
hi(0, "phpClass", { fg = "#00ceb0" })
hi(0, "phpFunction", { fg = yellow })
hi(0, "phpInclude", { fg = "#369ce9" })
hi(0, "phpMethod", { fg = yellow })
hi(0, "phpMethodsVar", { fg = "#98dcff" })
hi(0, "phpRegion", { fg = "#00ceb0" })
hi(0, "phpStaticClasses", { fg = "#00ceb0" })
hi(0, "phpUseClass", { fg = "#00ceb0" })
hi(0, "pythonBoolean", { fg = "#369ce9" })
hi(0, "pythonBuiltinObj", { fg = "#98dcff" })
hi(0, "pythonBuiltinType", { fg = "#00ceb0" })
hi(0, "pythonClassDef", { fg = "#00ceb0" })
hi(0, "pythonClassVar", { fg = "#369ce9" })
hi(0, "pythonExClass", { fg = "#00ceb0" })
hi(0, "pythonException", { fg = "#d873d2" })
hi(0, "pythonNone", { fg = "#369ce9" })
hi(0, "pythonOperator", { fg = "#369ce9" })
hi(0, "pythonStatement", { fg = "#369ce9" })
hi(0, "pythonTodo", { fg = "#369ce9" })
hi(0, "rubyClassName", { fg = "#00ceb0" })
hi(0, "rubyClassNameTag", { fg = "#00ceb0" })
hi(0, "rubyConstant", { fg = "#00ceb0" })
hi(0, "rubyModuleName", { fg = "#00ceb0" })
hi(0, "shDeref", { fg = "#98dcff" })
hi(0, "shVariable", { fg = "#98dcff" })
hi(0, "sqlFunction", { fg = "#e0b85e" })
hi(0, "sqlKeyword", { fg = "#d873d2" })
hi(0, "sqlOperator", { fg = "#d873d2" })
hi(0, "texBeginEnd", { fg = yellow })
hi(0, "texBeginEndModifier", { fg = "#98dcff" })
hi(0, "texBeginEndName", { fg = "#98dcff" })
hi(0, "texDocType", { fg = "#d873d2" })
hi(0, "texDocTypeArgs", { fg = "#98dcff" })
hi(0, "texOption", { fg = "#98dcff" })
hi(0, "texStatement", { fg = "#369ce9" })
hi(0, "typescriptAccessibilityModifier", { fg = "#369ce9" })
hi(0, "typescriptAliasDeclaration", { fg = "#00ceb0" })
hi(0, "typescriptAliasKeyword", { fg = "#369ce9" })
hi(0, "typescriptAmbientDeclaration", { fg = "#369ce9" })
hi(0, "typescriptArray", { fg = yellow })
hi(0, "typescriptArrowFunc", { fg = "#369ce9" })
hi(0, "typescriptArrowFuncArg", { fg = "#98dcff" })
hi(0, "typescriptAsyncFuncKeyword", { fg = "#369ce9" })
hi(0, "typescriptBOM", { fg = "#98dcff" })
hi(0, "typescriptBlock", { fg = "#98dcff" })
hi(0, "typescriptBraces", { fg = "#d4d4d4" })
hi(0, "typescriptCall", { fg = "#369ce9" })
hi(0, "typescriptCase", { fg = "#98dcff" })
hi(0, "typescriptCastKeyword", { fg = "#98dcff" })
hi(0, "typescriptClassBlock", { fg = "#98dcff" })
hi(0, "typescriptClassExtends", { fg = "#369ce9" })
hi(0, "typescriptClassHeritage", { fg = "#00ceb0" })
hi(0, "typescriptClassKeyword", { fg = "#369ce9" })
hi(0, "typescriptClassName", { fg = "#00ceb0" })
hi(0, "typescriptConditionalParen", { fg = "#98dcff" })
hi(0, "typescriptDOMDocProp", { fg = "#98dcff" })
hi(0, "typescriptDecorator", { fg = yellow })
hi(0, "typescriptDefault", { fg = "#98dcff" })
hi(0, "typescriptDocComment", { fg = "#00ceb0" })
hi(0, "typescriptDocTags", { fg = "#369ce9" })
hi(0, "typescriptES6SetProp", { fg = "#98dcff" })
hi(0, "typescriptEndColons", { fg = "#98dcff" })
hi(0, "typescriptEnum", { fg = "#00ceb0" })
hi(0, "typescriptEnumKeyword", { fg = "#369ce9" })
hi(0, "typescriptExceptions", { fg = "#98dcff" })
hi(0, "typescriptExport", { fg = "#d873d2" })
hi(0, "typescriptFuncCallArg", { fg = "#98dcff" })
hi(0, "typescriptFuncComma", { fg = "#98dcff" })
hi(0, "typescriptFuncKeyword", { fg = "#369ce9" })
hi(0, "typescriptFuncTypeArrow", { fg = "#369ce9" })
hi(0, "typescriptGlobal", { fg = "#00ceb0" })
hi(0, "typescriptGlobalMethod", { fg = yellow })
hi(0, "typescriptImport", { fg = "#d873d2" })
hi(0, "typescriptIndexExpr", { fg = "#98dcff" })
hi(0, "typescriptInterfaceExtends", { fg = "#369ce9" })
hi(0, "typescriptInterfaceHeritage", { fg = "#00ceb0" })
hi(0, "typescriptInterfaceKeyword", { fg = "#369ce9" })
hi(0, "typescriptInterfaceName", { fg = "#00ceb0" })
hi(0, "typescriptLabel", { fg = "#98dcff" })
hi(0, "typescriptLogicSymbols", { fg = "#98dcff" })
hi(0, "typescriptLoopParen", { fg = "#98dcff" })
hi(0, "typescriptMember", { fg = yellow })
hi(0, "typescriptMethodAccessor", { fg = "#369ce9" })
hi(0, "typescriptModule", { fg = "#98dcff" })
hi(0, "typescriptObjectLiteral", { fg = "#98dcff" })
hi(0, "typescriptOperator", { fg = "#369ce9" })
hi(0, "typescriptParamImpl", { fg = "#98dcff" })
hi(0, "typescriptParenExp", { fg = "#98dcff" })
hi(0, "typescriptParens", { fg = "#d4d4d4" })
hi(0, "typescriptPredefinedType", { fg = "#00ceb0" })
hi(0, "typescriptPromiseMethod", { fg = yellow })
hi(0, "typescriptReserved", { fg = "#d873d2" })
hi(0, "typescriptTemplateSB", { fg = "#e0b85e" })
hi(0, "typescriptTemplateSubstitution", { fg = "#98dcff" })
hi(0, "typescriptTypeParameter", { fg = "#00ceb0" })
hi(0, "typescriptTypeReference", { fg = "#00ceb0" })
hi(0, "typescriptVariable", { fg = "#369ce9" })
hi(0, "typescriptVariableDeclaration", { fg = "#98dcff" })
hi(0, "xmlEndTag", { fg = "#369ce9" })
hi(0, "xmlTag", { fg = "#369ce9" })
hi(0, "xmlTagName", { fg = "#369ce9" })
hi(0, "yamlConstant", { fg = "#369ce9" })
hi(0, "yamlKey", { fg = "#369ce9" })

-- Terminal colors
local g = vim.g

g.terminal_color_1 = "#f44747"
g.terminal_color_2 = "#6a9955"
g.terminal_color_3 = "#dcdcaa"
g.terminal_color_4 = "#569cd6"
g.terminal_color_5 = "#c586c0"
g.terminal_color_6 = "#4ec9b0"
g.terminal_color_7 = "#d4d4d4"
g.terminal_color_8 = "#808080"
g.terminal_color_9 = "#f44747"
g.terminal_color_10 = "#6a9955"
g.terminal_color_11 = "#dcdcaa"
g.terminal_color_12 = "#569cd6"
g.terminal_color_13 = "#c586c0"
g.terminal_color_14 = "#4ec9b0"
g.terminal_color_15 = "#d4d4d4"
